name = "lego-finder"
main = "frontend/index-prod.html"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "lego-finder.pages.dev", zone_name = "pages.dev" }
]

[triggers]
crons = []

[[routes]]
pattern = "/api/*"
zone_name = "pages.dev"
